#!/usr/bin/sh

# This file was autogenerated using the repository configuration tool at https://github.com/achianumba/repo.
# ALL MANUAL CHANGES WILL BE OVERWRITTEN THE NEXT TIME THE REPOSITORY CONFIGURATION TOOL RUNS!!!

cargo doc
miniserve --pretty-urls --index repo/index.html target/doc
