#!/usr/bin/sh

# This file was autogenerated using the repository configuration tool at https://github.com/achianumba/repo.
# ALL MANUAL CHANGES WILL BE OVERWRITTEN THE NEXT TIME THE REPOSITORY CONFIGURATION TOOL RUNS!!!

[ -n $(command -v git) ] && [ -n $(command -v code) ] && git config --global core.editor 'code --wait'

cargo doc --no-deps
cargo install miniserve
