#!/usr/bin/sh

# This file was autogenerated using the repository configuration tool at https://github.com/achianumba/repo.
# ALL MANUAL CHANGES WILL BE OVERWRITTEN THE NEXT TIME THE REPOSITORY CONFIGURATION TOOL RUNS!!!

[ -n $(command -v git) ] && [ -n $(command -v code) ] && git config --global core.editor 'code --wait'

sudo apt-get install -y libgpgme11-dev
rustup component add rustfmt-x86_64-unknown-linux-gnu
cargo doc --no-deps
cargo install miniserve
